### ISSUE TITLE
TODO List: Follow-up on #68

### ISSUE THREAD

**Issue by Luashine** [lep/jassdoc#69]
* [ ] **StringHash** In what version was it changed?

* [ ] boolexpr.j: Does inheritance matter when choosing which destroy function to use? Memory leaks or anything by calling the "wrong" function?

* [ ] Research Filter, Condition. The old descriptions contradict 1.32.10 tests

**Comment by lep** [comment]
1. 1.30.1 or earlier
2. I don't think so as `Filter` and `Condition` produce the exact same handle (when called on a function literal)
3. How so?
